In [1]:
# Simple program
def my_function():
  print("Hello from a function")

my_function()

Hello from a function

In [2]:

# A function
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus

In [3]:
# Arguments and functions
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

# Another Argument and function example
def my_progrm(ofstudy):
    print(ofstudy + "  InDs")
my_progrm(" ICT Department")
my_progrm(" Doing Data Science")
my_progrm(" In Second Year")

Emil Refsnes
Tobias Refsnes
Linus Refsnes
 ICT Department  InDs
 Doing Data Science  InDs
 In Second Year  InDs

In [4]:
# Working with libriaries!
import math
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import seaborn as sns;sns.set()
from IPython.display import display, HTML
from patsy import dmatrices
import warnings
warnings.filterwarnings ("ignore")
%pylab inline

Matplotlib is building the font cache; this may take a moment.

Populating the interactive namespace from numpy and matplotlib

In [6]:
nkhatabay_cohort = pd.read_csv(r"C:\Users\Learning\Documents\_MZUNI\LEVEL2\SEM1\INTRO TO CLOUD COMPUTING-BICT2307\GitSkills\Nkhata Bay District Hospital.csv")

In [9]:
nkhatabay_cohort.shape

(45, 7)

In [11]:
cohort = pd.DataFrame(nkhatabay_cohort)
cohort

,#,Age group,Gender,Tx new (new on ART),TX curr (receiving ART),TX curr (received IPT),TX curr (screened for TB)
0,1,<1 year,Female,1.0,1.0,0.0,1.0
1,2,1-4 years,Female,0.0,10.0,0.0,10.0
2,3,5-9 years,Female,0.0,23.0,0.0,23.0
3,4,10-14 years,Female,0.0,30.0,0.0,30.0
4,5,15-19 years,Female,4.0,48.0,3.0,48.0
5,6,20-24 years,Female,4.0,96.0,8.0,96.0
6,7,25-29 years,Female,1.0,156.0,10.0,156.0
7,8,30-34 years,Female,6.0,177.0,11.0,177.0
8,9,35-39 years,Female,5.0,356.0,8.0,356.0
9,10,40-44 years,Female,1.0,348.0,3.0,347.0
10,11,45-49 years,Female,5.0,279.0,4.0,278.0
11,12,50-54 years,Female,1.0,225.0,2.0,225.0
12,13,55-59 years,Female,0.0,164.0,0.0,164.0
13,14,60-64 years,Female,0.0,72.0,0.0,72.0
14,15,65-69 years,Female,0.0,31.0,0.0,31.0
15,16,70-74 years,Female,0.0,14.0,0.0,14.0
16,17,75-79 years,Female,0.0,0.0,0.0,0.0
17,18,80-84 years,Female,0.0,3.0,0.0,3.0
18,19,85-89 years,Female,0.0,0.0,0.0,0.0
19,20,90 plus years,Female,0.0,0.0,0.0,0.0
20,21,<1 year,Male,2.0,2.0,0.0,2.0
21,22,1-4 years,Male,1.0,14.0,1.0,14.0
22,23,5-9 years,Male,0.0,13.0,0.0,13.0
23,24,10-14 years,Male,1.0,29.0,1.0,29.0
24,25,15-19 years,Male,0.0,35.0,0.0,35.0
25,26,20-24 years,Male,0.0,20.0,0.0,20.0
26,27,25-29 years,Male,4.0,34.0,7.0,34.0
27,28,30-34 years,Male,4.0,63.0,7.0,63.0
28,29,35-39 years,Male,3.0,143.0,9.0,143.0
29,30,40-44 years,Male,1.0,199.0,4.0,199.0
30,31,45-49 years,Male,9.0,235.0,13.0,235.0
31,32,50-54 years,Male,0.0,180.0,1.0,180.0
32,33,55-59 years,Male,1.0,132.0,2.0,132.0
33,34,60-64 years,Male,1.0,96.0,2.0,96.0
34,35,65-69 years,Male,0.0,43.0,0.0,43.0
35,36,70-74 years,Male,0.0,25.0,0.0,25.0
36,37,75-79 years,Male,1.0,10.0,0.0,10.0
37,38,80-84 years,Male,0.0,4.0,0.0,4.0
38,39,85-89 years,Male,0.0,1.0,0.0,1.0
39,40,90 plus years,Male,0.0,0.0,0.0,0.0
40,41,All,Male,28.0,1278.0,47.0,1278.0
41,42,All,FP,6.0,102.0,1.0,102.0
42,43,All,FNP,18.0,1704.0,22.0,1702.0
43,44,All,FBf,4.0,227.0,26.0,227.0
44,Date Created: 2022-04-26:3:2:38 ...,NaN,NaN,NaN,NaN,NaN,NaN